# Branch Protection Rules Configuration
# This file documents the recommended branch protection settings for this repository
# Apply these settings via GitHub UI: Settings > Branches > Add rule

# Branch: main
# Protection Rules:
protection_rules:
  main:
    # Require pull request reviews before merging
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
      require_last_push_approval: false
    
    # Require status checks to pass before merging
    required_status_checks:
      strict: true  # Require branches to be up to date before merging
      checks:
        - "All Checks Passed"  # Our workflow's final status check
    
    # Additional protections
    enforce_admins: false  # Allow admins to bypass these rules
    required_linear_history: false
    allow_force_pushes: false
    allow_deletions: false
    required_conversation_resolution: true  # Require PR conversations to be resolved
    
    # Auto-merge settings (optional)
    # allow_auto_merge: true
    # delete_branch_on_merge: true

# To apply these settings via GitHub CLI:
# gh api repos/:owner/:repo/branches/main/protection \
#   --method PUT \
#   --field required_status_checks='{"strict":true,"checks":[{"context":"All Checks Passed"}]}' \
#   --field required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true}' \
#   --field restrictions=null \
#   --field enforce_admins=false \
#   --field required_linear_history=false \
#   --field allow_force_pushes=false \
#   --field allow_deletions=false \
#   --field required_conversation_resolution=true